safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     [ sass, Rakefile, codekit-config.json ]

future:      true
lsi:         false
pygments:    true
markdown:    kramdown
permalink:   /:year/:month/:day/:title
paginate:    10

kramdown:
  auto_ids: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
